// List of shortcut questions with OS-specific keys (Simplified: No sequence)
export const shortcutsList = [
  {
    id: 1,
    name: '列を選択',
    category: '一般的な操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'space']], mac: [['ctrl', 'space']] },
  },
  {
    id: 2,
    name: '行を選択する',
    category: '一般的な操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['shift', 'space']], mac: [['shift', 'space']] },
  },
  {
    id: 3,
    name: 'すべて選択',
    category: '一般的な操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'a']], mac: [['cmd', 'a']] },
  },
  {
    id: 4,
    name: '元に戻す',
    category: '一般的な操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'z']], mac: [['cmd', 'z']] },
  },
  {
    id: 5,
    name: 'やり直す',
    category: '一般的な操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'y']], mac: [['cmd', 'y']] },
  },
  {
    id: 6,
    name: '検索',
    category: '一般的な操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'f']], mac: [['cmd', 'f']] },
  },
  {
    id: 7,
    name: '検索と置換',
    category: '一般的な操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'h']], mac: [['cmd', 'shift', 'h']] },
  },
  {
    id: 8,
    name: '範囲へコピー',
    category: '一般的な操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'enter']], mac: [['cmd', 'enter']] },
  },
  {
    id: 9,
    name: '下方向へコピー',
    category: '一般的な操作',
    frequency: '高',
    level: '中級',
    keys: { windows: [['ctrl', 'd']], mac: [['cmd', 'd']] },
  },
  {
    id: 10,
    name: '右方向へコピー',
    category: '一般的な操作',
    frequency: '高',
    level: '中級',
    keys: { windows: [['ctrl', 'r']], mac: [['cmd', 'r']] },
  },
  {
    id: 11,
    name: 'コピー',
    category: '一般的な操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'c']], mac: [['cmd', 'c']] },
  },
  {
    id: 12,
    name: '切り取り',
    category: '一般的な操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'x']], mac: [['cmd', 'x']] },
  },
  {
    id: 13,
    name: '貼り付け',
    category: '一般的な操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'v']], mac: [['cmd', 'v']] },
  },
  {
    id: 14,
    name: '値のみ貼り付け',
    category: '一般的な操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'shift', 'v']], mac: [['cmd', 'shift', 'v']] },
  },
  {
    id: 15,
    name: '一般的なキーボード ショートカットを表示',
    category: '一般的な操作',
    frequency: '低',
    level: '上級',
    keys: { windows: [['ctrl', '/']], mac: [['cmd', '/']] },
  },
  {
    id: 16,
    name: '新しいシートを挿入',
    category: '一般的な操作',
    frequency: '高',
    level: '中級',
    keys: { windows: [['shift', 'f11']], mac: [['shift', 'fn', 'f11']] },
  },
  {
    id: 17,
    name: '太字',
    category: 'セルの書式設定',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'b']], mac: [['cmd', 'b']] },
  },
  {
    id: 18,
    name: '下線',
    category: 'セルの書式設定',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'u']], mac: [['cmd', 'u']] },
  },
  {
    id: 19,
    name: '斜体',
    category: 'セルの書式設定',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'i']], mac: [['cmd', 'i']] },
  },
  {
    id: 20,
    name: '取り消し線',
    category: 'セルの書式設定',
    frequency: '低',
    level: '上級',
    keys: {
      windows: [['alt', 'shift', '5']],
      mac: [['option', 'shift', '5']],
    },
  },
  {
    id: 21,
    name: '中央揃え',
    category: 'セルの書式設定',
    frequency: '高',
    level: '中級',
    keys: { windows: [['ctrl', 'shift', 'e']], mac: [['cmd', 'shift', 'e']] },
  },
  {
    id: 22,
    name: '左揃え',
    category: 'セルの書式設定',
    frequency: '高',
    level: '中級',
    keys: { windows: [['ctrl', 'shift', 'l']], mac: [['cmd', 'shift', 'l']] },
  },
  {
    id: 23,
    name: '右揃え',
    category: 'セルの書式設定',
    frequency: '高',
    level: '中級',
    keys: { windows: [['ctrl', 'shift', 'r']], mac: [['cmd', 'shift', 'r']] },
  },
  {
    id: 24,
    name: '上枠線を適用',
    category: 'セルの書式設定',
    frequency: '高',
    level: '中級',
    keys: { windows: [['alt', 'shift', '1']], mac: [['option', 'shift', '1']] },
  },
  {
    id: 25,
    name: '右枠線を適用',
    category: 'セルの書式設定',
    frequency: '高',
    level: '中級',
    keys: { windows: [['alt', 'shift', '2']], mac: [['option', 'shift', '2']] },
  },
  {
    id: 26,
    name: '下枠線を適用',
    category: 'セルの書式設定',
    frequency: '高',
    level: '中級',
    keys: { windows: [['alt', 'shift', '3']], mac: [['option', 'shift', '3']] },
  },
  {
    id: 27,
    name: '左枠線を適用',
    category: 'セルの書式設定',
    frequency: '高',
    level: '中級',
    keys: { windows: [['alt', 'shift', '4']], mac: [['option', 'shift', '4']] },
  },
  {
    id: 28,
    name: '枠線を削除',
    category: 'セルの書式設定',
    frequency: '高',
    level: '中級',
    keys: { windows: [['alt', 'shift', '6']], mac: [['option', 'shift', '6']] },
  },
  {
    id: 29,
    name: 'リンクを挿入',
    category: 'セルの書式設定',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'k']], mac: [['cmd', 'k']] },
  },
  {
    id: 30,
    name: '表示形式を小数に設定',
    category: 'セルの書式設定',
    frequency: '低',
    level: '上級',
    keys: { windows: [['ctrl', 'shift', '1']], mac: [['ctrl', 'shift', '1']] },
  },
  {
    id: 31,
    name: '表示形式を時刻に設定',
    category: 'セルの書式設定',
    frequency: '低',
    level: '上級',
    keys: { windows: [['ctrl', 'shift', '2']], mac: [['ctrl', 'shift', '2']] },
  },
  {
    id: 32,
    name: '表示形式を日付に設定',
    category: 'セルの書式設定',
    frequency: '低',
    level: '上級',
    keys: { windows: [['ctrl', 'shift', '3']], mac: [['ctrl', 'shift', '3']] },
  },
  {
    id: 33,
    name: '表示形式を通貨に設定',
    category: 'セルの書式設定',
    frequency: '低',
    level: '上級',
    keys: { windows: [['ctrl', 'shift', '4']], mac: [['ctrl', 'shift', '4']] },
  },
  {
    id: 34,
    name: '表示形式をパーセンテージに設定',
    category: 'セルの書式設定',
    frequency: '低',
    level: '上級',
    keys: { windows: [['ctrl', 'shift', '5']], mac: [['ctrl', 'shift', '5']] },
  },
  {
    id: 35,
    name: '表示形式を指数に設定',
    category: 'セルの書式設定',
    frequency: '低',
    level: '上級',
    keys: { windows: [['ctrl', 'shift', '6']], mac: [['ctrl', 'shift', '6']] },
  },
  {
    id: 36,
    name: '次のシートに移動',
    category: 'スプレッドシートの操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['alt', 'arrowdown']], mac: [['option', 'arrowdown']] },
  },
  {
    id: 37,
    name: '前のシートに移動',
    category: 'スプレッドシートの操作',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['alt', 'arrowup']], mac: [['option', 'arrowup']] },
  },
  {
    id: 38,
    name: 'シートリストを表示',
    category: 'スプレッドシートの操作',
    frequency: '高',
    level: '中級',
    keys: { windows: [['alt', 'shift', 'k']], mac: [['option', 'shift', 'k']] },
  },
  {
    id: 39,
    name: 'ハイパーリンクを開く',
    category: 'スプレッドシートの操作',
    frequency: '高',
    level: '中級',
    keys: { windows: [['alt', 'enter']], mac: [['option', 'enter']] },
  },
  {
    id: 40,
    name: 'メモを挿入、編集',
    category: 'スプレッドシートの操作',
    frequency: '高',
    level: '中級',
    keys: { windows: [['shift', 'f2']], mac: [['shift', 'fn', 'f2']] },
  },
  {
    id: 41,
    name: '行を上に挿入',
    category: '行と列の追加や変更',
    frequency: '激高',
    level: '初級',
    keys: {
      windows: [['ctrl', 'alt', '=']],
      mac: [
        ['cmd', 'option', '='],
        ['cmd', 'option', 'shift', '-'],
      ],
    },
  },
  {
    id: 42,
    name: '列を左に挿入',
    category: '行と列の追加や変更',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'alt', '=']], mac: [['cmd', 'option', '=']] },
  },
  {
    id: 43,
    name: '行を削除',
    category: '行と列の追加や変更',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'alt', '-']], mac: [['cmd', 'option', '-']] },
  },
  {
    id: 44,
    name: '列を削除',
    category: '行と列の追加や変更',
    frequency: '激高',
    level: '初級',
    keys: { windows: [['ctrl', 'alt', '-']], mac: [['cmd', 'option', '-']] },
  },
  {
    id: 45,
    name: '行を非表示',
    category: '行と列の追加や変更',
    frequency: '中',
    level: '上級',
    keys: { windows: [['ctrl', 'alt', '9']], mac: [['cmd', 'option', '9']] },
  },
  {
    id: 46,
    name: '行を再表示',
    category: '行と列の追加や変更',
    frequency: '中',
    level: '上級',
    keys: { windows: [['ctrl', 'shift', '9']], mac: [['cmd', 'shift', '9']] },
  },
  {
    id: 47,
    name: '列を非表示',
    category: '行と列の追加や変更',
    frequency: '中',
    level: '上級',
    keys: { windows: [['ctrl', 'alt', '0']], mac: [['cmd', 'option', '0']] },
  },
  {
    id: 48,
    name: '列を再表示',
    category: '行と列の追加や変更',
    frequency: '中',
    level: '上級',
    keys: { windows: [['ctrl', 'shift', '0']], mac: [['cmd', 'shift', '0']] },
  },
  {
    id: 49,
    name: '行または列をグループ化',
    category: '行と列の追加や変更',
    frequency: '高',
    level: '中級',
    keys: { windows: [['alt', 'shift', 'arrowright']], mac: [['option', 'shift', 'arrowright']] },
  },
  {
    id: 50,
    name: '行または列のグループ化を解除',
    category: '行と列の追加や変更',
    frequency: '高',
    level: '中級',
    keys: { windows: [['alt', 'shift', 'arrowleft']], mac: [['option', 'shift', 'arrowleft']] },
  },
  {
    id: 51,
    name: 'グループ化した行または列を展開',
    category: '行と列の追加や変更',
    frequency: '高',
    level: '中級',
    keys: { windows: [['alt', 'shift', 'arrowdown']], mac: [['option', 'shift', 'arrowdown']] },
  },
  {
    id: 52,
    name: 'グループ化した行または列を折りたたむ',
    category: '行と列の追加や変更',
    frequency: '高',
    level: '中級',
    keys: { windows: [['alt', 'shift', 'arrowup']], mac: [['option', 'shift', 'arrowup']] },
  },
]
